name: deploy1.yml
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: corretto
      - name: Install Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Bump Version
        id: bump
        run: |
          set -e
          
          mvn -B -q build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
          
          VER="$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)"
          echo "Nova Versao: $VER"
          echo "version=$VER" >> "$GITHUB_OUTPUT"
      - name: Build Project
        run: |
          mvn -B -q -DskipTests package
      - name: Copy Artefato
        run: |
          cp target/*.jar docker/app.jar
      - name: View Files
        run: |
          ls docker/
          
      - name: Build Docker
        run: |
          cd docker
          VER=${{steps.bump.outputs.version}}
          echo "Nova Versao: $VER"
          docker build . -t leogloriainfnet/cervejaria-devops:${{steps.bump.outputs.version}}  
